service: lambda-sandbox

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  hello:
    handler: src/welcome.hello

custom:
  webpack:
    packager: 'yarn'
